from test_coverage.all_test_cases import Tests

"""
## PURPOSE
The purpose of this test is to check wholesale calculations when an master data is updated on an MP.

## CASES TESTED
"""
Tests.CalculationTests.MeteringPointMasterDataUpdates.Change_of_resolution_on_an_MP
Tests.CalculationTests.MeteringPointMasterDataUpdates.Change_of_energy_supplier_on_an_MP
Tests.CalculationTests.MeteringPointMasterDataUpdates.Change_of_balance_responsible_on_an_MP
Tests.CalculationTests.MeteringPointMasterDataUpdates.Energy_Supplier_change_on_Grid_Loss_MP
Tests.CalculationTests.MeteringPointMasterDataUpdates.Energy_Supplier_change_on_System_Correction_MP
Tests.CalculationTests.MeteringPointMasterDataUpdates.Balance_Responsible_change_on_Grid_Loss_MP
Tests.CalculationTests.MeteringPointMasterDataUpdates.Balance_Responsible_change_on_System_Correction_MP
