# yamllint disable rule:quoted-strings
version: 2
updates:
  - package-ecosystem: "terraform"
    directories:
      - "/dh2-bridge/**/*"
    schedule:
      interval: "monthly"
      time: "08:00"
      timezone: "Europe/Copenhagen"
    open-pull-requests-limit: 1
    commit-message:
      prefix: "dh2-bridge"
    assignees:
      - "NicolajAaH"
      - "renenielsendk"
      - "kerbou"
      - "djorgensendk"
      - "lanni-energinet"
    groups:
      providers:
        patterns:
          - "*"
  - package-ecosystem: "terraform"
    directories:
      - "/edi/**/*"
    schedule:
      interval: "monthly"
      time: "08:00"
      timezone: "Europe/Copenhagen"
    open-pull-requests-limit: 1
    commit-message:
      prefix: "edi"
    assignees:
      - "NicolajAaH"
      - "renenielsendk"
      - "kerbou"
      - "djorgensendk"
      - "lanni-energinet"
    groups:
      providers:
        patterns:
          - "*"
  - package-ecosystem: "terraform"
    directories:
      - "/grid-loss-imbalance-prices/**/*"
    schedule:
      interval: "monthly"
      time: "08:00"
      timezone: "Europe/Copenhagen"
    open-pull-requests-limit: 1
    commit-message:
      prefix: "grid-loss-imbalance-prices"
    assignees:
      - "NicolajAaH"
      - "renenielsendk"
      - "kerbou"
      - "djorgensendk"
      - "lanni-energinet"
    groups:
      providers:
        patterns:
          - "*"
  - package-ecosystem: "terraform"
    directories:
      - "/esett-exchange/**/*"
    schedule:
      interval: "monthly"
      time: "08:00"
      timezone: "Europe/Copenhagen"
    open-pull-requests-limit: 1
    commit-message:
      prefix: "esett-exchange"
    assignees:
      - "NicolajAaH"
      - "renenielsendk"
      - "kerbou"
      - "djorgensendk"
      - "lanni-energinet"
    groups:
      providers:
        patterns:
          - "*"
  - package-ecosystem: "terraform"
    directories:
      - "/integration-test/**/*"
    schedule:
      interval: "monthly"
      time: "08:00"
      timezone: "Europe/Copenhagen"
    open-pull-requests-limit: 1
    commit-message:
      prefix: "integration-test"
    assignees:
      - "NicolajAaH"
      - "renenielsendk"
      - "kerbou"
      - "djorgensendk"
      - "lanni-energinet"
    groups:
      providers:
        patterns:
          - "*"
  - package-ecosystem: "terraform"
    directories:
      - "/market-participant/**/*"
    schedule:
      interval: "monthly"
      time: "08:00"
      timezone: "Europe/Copenhagen"
    open-pull-requests-limit: 1
    commit-message:
      prefix: "market-participant"
    assignees:
      - "NicolajAaH"
      - "renenielsendk"
      - "kerbou"
      - "djorgensendk"
      - "lanni-energinet"
    groups:
      providers:
        patterns:
          - "*"
  - package-ecosystem: "terraform"
    directories:
      - "/migrations/**/*"
    schedule:
      interval: "monthly"
      time: "08:00"
      timezone: "Europe/Copenhagen"
    open-pull-requests-limit: 1
    commit-message:
      prefix: "migrations"
    assignees:
      - "NicolajAaH"
      - "renenielsendk"
      - "kerbou"
      - "djorgensendk"
      - "lanni-energinet"
    groups:
      providers:
        patterns:
          - "*"
  - package-ecosystem: "terraform"
    directories:
      - "/revision-log/**/*"
    schedule:
      interval: "monthly"
      time: "08:00"
      timezone: "Europe/Copenhagen"
    open-pull-requests-limit: 1
    commit-message:
      prefix: "revision-log"
    assignees:
      - "NicolajAaH"
      - "renenielsendk"
      - "kerbou"
      - "djorgensendk"
      - "lanni-energinet"
    groups:
      providers:
        patterns:
          - "*"
  - package-ecosystem: "terraform"
    directories:
      - "/sauron/**/*"
    schedule:
      interval: "monthly"
      time: "08:00"
      timezone: "Europe/Copenhagen"
    open-pull-requests-limit: 1
    commit-message:
      prefix: "sauron"
    assignees:
      - "NicolajAaH"
      - "renenielsendk"
      - "kerbou"
      - "djorgensendk"
      - "lanni-energinet"
    groups:
      providers:
        patterns:
          - "*"
  - package-ecosystem: "terraform"
    directories:
      - "/sauron-healthchecks-api/**/*"
    schedule:
      interval: "monthly"
      time: "08:00"
      timezone: "Europe/Copenhagen"
    open-pull-requests-limit: 1
    commit-message:
      prefix: "sauron-healthchecks-api"
    assignees:
      - "NicolajAaH"
      - "renenielsendk"
      - "kerbou"
      - "djorgensendk"
      - "lanni-energinet"
    groups:
      providers:
        patterns:
          - "*"
  - package-ecosystem: "terraform"
    directories:
      - "/settlement-report/**/*"
    schedule:
      interval: "monthly"
      time: "08:00"
      timezone: "Europe/Copenhagen"
    open-pull-requests-limit: 1
    commit-message:
      prefix: "settlement-report"
    assignees:
      - "NicolajAaH"
      - "renenielsendk"
      - "kerbou"
      - "djorgensendk"
      - "lanni-energinet"
    groups:
      providers:
        patterns:
          - "*"
  - package-ecosystem: "terraform"
    directories:
      - "/shared-resources/**/*"
    schedule:
      interval: "monthly"
      time: "08:00"
      timezone: "Europe/Copenhagen"
    open-pull-requests-limit: 1
    commit-message:
      prefix: "shared-resources"
    assignees:
      - "NicolajAaH"
      - "renenielsendk"
      - "kerbou"
      - "djorgensendk"
      - "lanni-energinet"
    groups:
      providers:
        patterns:
          - "*"
  - package-ecosystem: "terraform"
    directories:
      - "/ui/**/*"
    schedule:
      interval: "monthly"
      time: "08:00"
      timezone: "Europe/Copenhagen"
    open-pull-requests-limit: 1
    commit-message:
      prefix: "ui"
    assignees:
      - "NicolajAaH"
      - "renenielsendk"
      - "kerbou"
      - "djorgensendk"
      - "lanni-energinet"
    groups:
      providers:
        patterns:
          - "*"
  - package-ecosystem: "terraform"
    directories:
      - "/wholesale/**/*"
    schedule:
      interval: "monthly"
      time: "08:00"
      timezone: "Europe/Copenhagen"
    open-pull-requests-limit: 1
    commit-message:
      prefix: "wholesale"
    assignees:
      - "NicolajAaH"
      - "renenielsendk"
      - "kerbou"
      - "djorgensendk"
      - "lanni-energinet"
    groups:
      providers:
        patterns:
          - "*"
