# yamllint disable rule:quoted-strings
version: 2
updates:
  - package-ecosystem: "terraform"
    directories:
      - "/dh2-bridge/terraform/main/**"
    schedule:
      interval: "monthly"
      time: "08:00"
      timezone: "Europe/Copenhagen"
    open-pull-requests-limit: 1
    commit-message:
      prefix: "dh2-bridge"
    assignees:
      - "NicolajAaH"
      - "kerbou"
      - "djorgensendk"
      - "lanni-energinet"
      - "Karl-koder"
      - "yusuftezel03"
      - "ole-kaas"
    groups:
      providers:
        patterns:
          - "*"
  - package-ecosystem: "terraform"
    directories:
      - "/edi/terraform/main/**"
    schedule:
      interval: "monthly"
      time: "08:00"
      timezone: "Europe/Copenhagen"
    open-pull-requests-limit: 1
    commit-message:
      prefix: "edi"
    assignees:
      - "NicolajAaH"
      - "kerbou"
      - "djorgensendk"
      - "lanni-energinet"
      - "Karl-koder"
      - "yusuftezel03"
      - "ole-kaas"
    groups:
      providers:
        patterns:
          - "*"
  - package-ecosystem: "terraform"
    directories:
      - "/grid-loss-imbalance-prices/terraform/main/**"
    schedule:
      interval: "monthly"
      time: "08:00"
      timezone: "Europe/Copenhagen"
    open-pull-requests-limit: 1
    commit-message:
      prefix: "grid-loss-imbalance-prices"
    assignees:
      - "NicolajAaH"
      - "kerbou"
      - "djorgensendk"
      - "lanni-energinet"
      - "Karl-koder"
      - "yusuftezel03"
      - "ole-kaas"
    groups:
      providers:
        patterns:
          - "*"
  - package-ecosystem: "terraform"
    directories:
      - "/esett-exchange/terraform/main/**"
    schedule:
      interval: "monthly"
      time: "08:00"
      timezone: "Europe/Copenhagen"
    open-pull-requests-limit: 1
    commit-message:
      prefix: "esett-exchange"
    assignees:
      - "NicolajAaH"
      - "kerbou"
      - "djorgensendk"
      - "lanni-energinet"
      - "Karl-koder"
      - "yusuftezel03"
      - "ole-kaas"
    groups:
      providers:
        patterns:
          - "*"
  - package-ecosystem: "terraform"
    directories:
      - "/integration-test/terraform/main/**"
    schedule:
      interval: "monthly"
      time: "08:00"
      timezone: "Europe/Copenhagen"
    open-pull-requests-limit: 1
    commit-message:
      prefix: "integration-test"
    assignees:
      - "NicolajAaH"
      - "kerbou"
      - "djorgensendk"
      - "lanni-energinet"
      - "Karl-koder"
      - "yusuftezel03"
      - "ole-kaas"
    groups:
      providers:
        patterns:
          - "*"
  - package-ecosystem: "terraform"
    directories:
      - "/market-participant/terraform/main/**"
    schedule:
      interval: "monthly"
      time: "08:00"
      timezone: "Europe/Copenhagen"
    open-pull-requests-limit: 1
    commit-message:
      prefix: "market-participant"
    assignees:
      - "NicolajAaH"
      - "kerbou"
      - "djorgensendk"
      - "lanni-energinet"
      - "Karl-koder"
      - "yusuftezel03"
      - "ole-kaas"
    groups:
      providers:
        patterns:
          - "*"
  - package-ecosystem: "terraform"
    directories:
      - "/migrations/terraform/main/**"
    schedule:
      interval: "monthly"
      time: "08:00"
      timezone: "Europe/Copenhagen"
    open-pull-requests-limit: 1
    commit-message:
      prefix: "migrations"
    assignees:
      - "NicolajAaH"
      - "kerbou"
      - "djorgensendk"
      - "lanni-energinet"
      - "Karl-koder"
      - "yusuftezel03"
      - "ole-kaas"
    groups:
      providers:
        patterns:
          - "*"
  - package-ecosystem: "terraform"
    directories:
      - "/revision-log/terraform/main/**"
    schedule:
      interval: "monthly"
      time: "08:00"
      timezone: "Europe/Copenhagen"
    open-pull-requests-limit: 1
    commit-message:
      prefix: "revision-log"
    assignees:
      - "NicolajAaH"
      - "kerbou"
      - "djorgensendk"
      - "lanni-energinet"
      - "Karl-koder"
      - "yusuftezel03"
      - "ole-kaas"
    groups:
      providers:
        patterns:
          - "*"
  - package-ecosystem: "terraform"
    directories:
      - "/sauron/terraform/main/**"
    schedule:
      interval: "monthly"
      time: "08:00"
      timezone: "Europe/Copenhagen"
    open-pull-requests-limit: 1
    commit-message:
      prefix: "sauron"
    assignees:
      - "NicolajAaH"
      - "kerbou"
      - "djorgensendk"
      - "lanni-energinet"
      - "Karl-koder"
      - "yusuftezel03"
      - "ole-kaas"
    groups:
      providers:
        patterns:
          - "*"
  - package-ecosystem: "terraform"
    directories:
      - "/sauron-healthchecks-api/terraform/main/**"
    schedule:
      interval: "monthly"
      time: "08:00"
      timezone: "Europe/Copenhagen"
    open-pull-requests-limit: 1
    commit-message:
      prefix: "sauron-healthchecks-api"
    assignees:
      - "NicolajAaH"
      - "kerbou"
      - "djorgensendk"
      - "lanni-energinet"
      - "Karl-koder"
      - "yusuftezel03"
      - "ole-kaas"
    groups:
      providers:
        patterns:
          - "*"
  - package-ecosystem: "terraform"
    directories:
      - "/settlement-report/terraform/main/**"
    schedule:
      interval: "monthly"
      time: "08:00"
      timezone: "Europe/Copenhagen"
    open-pull-requests-limit: 1
    commit-message:
      prefix: "settlement-report"
    assignees:
      - "NicolajAaH"
      - "kerbou"
      - "djorgensendk"
      - "lanni-energinet"
      - "Karl-koder"
      - "yusuftezel03"
      - "ole-kaas"
    groups:
      providers:
        patterns:
          - "*"
  - package-ecosystem: "terraform"
    directories:
      - "/shared-resources/terraform/b2c/main/**"
      - "/shared-resources/terraform/infrastructure/main/**"
    schedule:
      interval: "monthly"
      time: "08:00"
      timezone: "Europe/Copenhagen"
    open-pull-requests-limit: 1
    commit-message:
      prefix: "shared-resources"
    assignees:
      - "NicolajAaH"
      - "kerbou"
      - "djorgensendk"
      - "lanni-energinet"
      - "Karl-koder"
      - "yusuftezel03"
      - "ole-kaas"
    groups:
      providers:
        patterns:
          - "*"
  - package-ecosystem: "terraform"
    directories:
      - "/ui/terraform/main/**"
    schedule:
      interval: "monthly"
      time: "08:00"
      timezone: "Europe/Copenhagen"
    open-pull-requests-limit: 1
    commit-message:
      prefix: "ui"
    assignees:
      - "NicolajAaH"
      - "kerbou"
      - "djorgensendk"
      - "lanni-energinet"
      - "Karl-koder"
      - "yusuftezel03"
      - "ole-kaas"
    groups:
      providers:
        patterns:
          - "*"
  - package-ecosystem: "terraform"
    directories:
      - "/wholesale/terraform/main/**"
    schedule:
      interval: "monthly"
      time: "08:00"
      timezone: "Europe/Copenhagen"
    open-pull-requests-limit: 1
    commit-message:
      prefix: "wholesale"
    assignees:
      - "NicolajAaH"
      - "kerbou"
      - "djorgensendk"
      - "lanni-energinet"
      - "Karl-koder"
      - "yusuftezel03"
      - "ole-kaas"
    groups:
      providers:
        patterns:
          - "*"
  - package-ecosystem: "terraform"
    directories:
      - "/measurements/terraform/core/main/**"
    schedule:
      interval: "monthly"
      time: "08:00"
      timezone: "Europe/Copenhagen"
    open-pull-requests-limit: 1
    commit-message:
      prefix: "measurements-core"
    assignees:
      - "NicolajAaH"
      - "kerbou"
      - "djorgensendk"
      - "lanni-energinet"
      - "Karl-koder"
      - "yusuftezel03"
      - "ole-kaas"
    groups:
      providers:
        patterns:
          - "*"
  - package-ecosystem: "terraform"
    directories:
      - "/measurements/terraform/capacity-settlement/main/**"
    schedule:
      interval: "monthly"
      time: "08:00"
      timezone: "Europe/Copenhagen"
    open-pull-requests-limit: 1
    commit-message:
      prefix: "measurements-capacity-settlement"
    assignees:
      - "NicolajAaH"
      - "kerbou"
      - "djorgensendk"
      - "lanni-energinet"
      - "Karl-koder"
      - "yusuftezel03"
      - "ole-kaas"
    groups:
      providers:
        patterns:
          - "*"
  - package-ecosystem: "terraform"
    directories:
      - "/measurements/terraform/electrical-heating/main/**"
    schedule:
      interval: "monthly"
      time: "08:00"
      timezone: "Europe/Copenhagen"
    open-pull-requests-limit: 1
    commit-message:
      prefix: "measurements-electrical-heating"
    assignees:
      - "NicolajAaH"
      - "kerbou"
      - "djorgensendk"
      - "lanni-energinet"
      - "Karl-koder"
      - "yusuftezel03"
      - "ole-kaas"
    groups:
      providers:
        patterns:
          - "*"
  - package-ecosystem: "terraform"
    directories:
      - "/archive/terraform/main/**"
    schedule:
      interval: "monthly"
      time: "08:00"
      timezone: "Europe/Copenhagen"
    open-pull-requests-limit: 1
    commit-message:
      prefix: "archive"
    assignees:
      - "NicolajAaH"
      - "kerbou"
      - "djorgensendk"
      - "lanni-energinet"
      - "Karl-koder"
      - "yusuftezel03"
      - "ole-kaas"
    groups:
      providers:
        patterns:
          - "*"
  - package-ecosystem: "terraform"
    directories:
      - "/electricity-market/terraform/main/**"
    schedule:
      interval: "monthly"
      time: "08:00"
      timezone: "Europe/Copenhagen"
    open-pull-requests-limit: 1
    commit-message:
      prefix: "electricity-market"
    assignees:
      - "NicolajAaH"
      - "kerbou"
      - "djorgensendk"
      - "lanni-energinet"
      - "Karl-koder"
      - "yusuftezel03"
      - "ole-kaas"
    groups:
      providers:
        patterns:
          - "*"
  - package-ecosystem: "terraform"
    directories:
      - "/notifications/terraform/main/**"
    schedule:
      interval: "monthly"
      time: "08:00"
      timezone: "Europe/Copenhagen"
    open-pull-requests-limit: 1
    commit-message:
      prefix: "notifications"
    assignees:
      - "NicolajAaH"
      - "kerbou"
      - "djorgensendk"
      - "lanni-energinet"
      - "Karl-koder"
      - "yusuftezel03"
      - "ole-kaas"
    groups:
      providers:
        patterns:
          - "*"
  - package-ecosystem: "terraform"
    directories:
      - "/process-manager/terraform/core/main/**"
    schedule:
      interval: "monthly"
      time: "08:00"
      timezone: "Europe/Copenhagen"
    open-pull-requests-limit: 1
    commit-message:
      prefix: "process-manager-core"
    assignees:
      - "NicolajAaH"
      - "kerbou"
      - "djorgensendk"
      - "lanni-energinet"
      - "Karl-koder"
      - "yusuftezel03"
      - "ole-kaas"
    groups:
      providers:
        patterns:
          - "*"
  - package-ecosystem: "terraform"
    directories:
      - "/process-manager/terraform/orchestrations/main/**"
    schedule:
      interval: "monthly"
      time: "08:00"
      timezone: "Europe/Copenhagen"
    open-pull-requests-limit: 1
    commit-message:
      prefix: "process-manager-orchestrations"
    assignees:
      - "NicolajAaH"
      - "kerbou"
      - "djorgensendk"
      - "lanni-energinet"
      - "Karl-koder"
      - "yusuftezel03"
      - "ole-kaas"
    groups:
      providers:
        patterns:
          - "*"
