name: Prepare dotnet outputs

#
# This action is called from:
#  - the 'dotnet-solution-ci.yml' file IF the workflow parameter PREPARE_OUTPUTS is set to 'true'.
#  - the 'dotnet-build-prerelease.yml' file.
#
# Prepared outputs will be zipped and uploaded as the 'dotnet' artifact.
#
# All 'apps' must be output into the '\functions\' subfolder, to match
# how they are later retrieved in the '<subsystem>-stage-deployment.yml' file.
#

inputs:
  output_path:
    required: true

runs:
  using: composite
  steps:
    - name: Publish Subsystem Tests
      shell: bash
      run: |
        dotnet publish \
          '.\source\dotnet\subsystem-tests\SubsystemTests.csproj' \
          --no-build \
          --no-restore \
          --configuration Release \
          --output '${{ inputs.output_path }}\subsystemtests'
