from spark_sql_migrations import Schema, Table, View

import package.infrastructure.paths as paths
from package.databases.migrations_wholesale.schemas import (
    grid_loss_metering_points_schema,
)
from package.databases.wholesale_results_internal.schemas import (
    energy_schema_uc,
    energy_per_brp_schema_uc,
    energy_per_es_schema_uc,
    grid_loss_metering_point_time_series_schema_uc,
    exchange_per_neighbor_schema_uc,
    amounts_per_charge_schema,
    monthly_amounts_schema_uc,
    total_monthly_amounts_schema_uc,
)

import package.databases.wholesale_basis_data_internal.schemas as basis_data_schemas

schema_config = [
    Schema(
        name=paths.WholesaleInternalDatabase.DATABASE_NAME,
        tables=[
            Table(
                name=paths.WholesaleInternalDatabase.CALCULATIONS_TABLE_NAME,
                schema=basis_data_schemas.calculations_schema,
            ),
            Table(
                name=paths.WholesaleInternalDatabase.GRID_LOSS_METERING_POINTS_TABLE_NAME,
                schema=grid_loss_metering_points_schema,
            ),
        ],
        views=[],
    ),
    Schema(
        name=paths.WholesaleResultsInternalDatabase.DATABASE_NAME,
        tables=[
            Table(
                name=paths.WholesaleResultsInternalDatabase.ENERGY_TABLE_NAME,
                schema=energy_schema_uc,
            ),
            Table(
                name=paths.WholesaleResultsInternalDatabase.ENERGY_PER_BRP_TABLE_NAME,
                schema=energy_per_brp_schema_uc,
            ),
            Table(
                name=paths.WholesaleResultsInternalDatabase.ENERGY_PER_ES_TABLE_NAME,
                schema=energy_per_es_schema_uc,
            ),
            Table(
                name=paths.WholesaleResultsInternalDatabase.EXCHANGE_PER_NEIGHBOR_TABLE_NAME,
                schema=exchange_per_neighbor_schema_uc,
            ),
            Table(
                name=paths.WholesaleResultsInternalDatabase.GRID_LOSS_METERING_POINT_TIME_SERIES_TABLE_NAME,
                schema=grid_loss_metering_point_time_series_schema_uc,
            ),
            Table(
                name=paths.WholesaleResultsInternalDatabase.AMOUNTS_PER_CHARGE_TABLE_NAME,
                schema=amounts_per_charge_schema,
            ),
            Table(
                name=paths.WholesaleResultsInternalDatabase.MONTHLY_AMOUNTS_PER_CHARGE_TABLE_NAME,
                schema=monthly_amounts_schema_uc,
            ),
            Table(
                name=paths.WholesaleResultsInternalDatabase.TOTAL_MONTHLY_AMOUNTS_TABLE_NAME,
                schema=total_monthly_amounts_schema_uc,
            ),
        ],
        views=[],
    ),
    Schema(
        name=paths.WholesaleBasisDataInternalDatabase.DATABASE_NAME,
        tables=[
            Table(
                name=paths.WholesaleBasisDataInternalDatabase.METERING_POINT_PERIODS_TABLE_NAME,
                schema=basis_data_schemas.metering_point_period_schema_uc,
            ),
            Table(
                name=paths.WholesaleBasisDataInternalDatabase.TIME_SERIES_POINTS_TABLE_NAME,
                schema=basis_data_schemas.time_series_point_schema,
            ),
            Table(
                name=paths.WholesaleBasisDataInternalDatabase.CHARGE_LINK_PERIODS_TABLE_NAME,
                schema=basis_data_schemas.charge_link_periods_schema_uc,
            ),
            Table(
                name=paths.WholesaleBasisDataInternalDatabase.CHARGE_PRICE_INFORMATION_PERIODS_TABLE_NAME,
                schema=basis_data_schemas.charge_price_information_periods_schema_uc,
            ),
            Table(
                name=paths.WholesaleBasisDataInternalDatabase.CHARGE_PRICE_POINTS_TABLE_NAME,
                schema=basis_data_schemas.charge_price_points_schema,
            ),
        ],
        views=[],
    ),
    Schema(
        name=paths.WholesaleResultsDatabase.DATABASE_NAME,
        tables=[],
        views=[
            View(
                name=paths.WholesaleResultsDatabase.AMOUNTS_PER_CHARGE_V1_VIEW_NAME,
            ),
            View(
                name=paths.WholesaleResultsDatabase.MONTHLY_AMOUNTS_PER_CHARGE_V1_VIEW_NAME,
            ),
            View(
                name=paths.WholesaleResultsDatabase.TOTAL_MONTHLY_AMOUNTS_V1_VIEW_NAME,
            ),
        ],
    ),
    Schema(
        name=paths.WholesaleSettlementReportsDatabase.DATABASE_NAME,
        tables=[],
        views=[
            View(
                name=paths.WholesaleSettlementReportsDatabase.METERING_POINT_PERIODS_VIEW_NAME_V1
            ),
            View(
                name=paths.WholesaleSettlementReportsDatabase.METERING_POINT_TIME_SERIES_VIEW_NAME_V1
            ),
            View(
                name=paths.WholesaleSettlementReportsDatabase.CHARGE_PRICES_VIEW_NAME_V1
            ),
            View(
                name=paths.WholesaleSettlementReportsDatabase.CHARGE_LINK_PERIODS_VIEW_NAME_V1
            ),
        ],
    ),
]
