from spark_sql_migrations import Schema, Table, View

import package.databases.wholesale_basis_data_internal.schemas as basis_data_schemas
import package.databases.wholesale_internal.schemas as internal_schemas
import package.infrastructure.paths as paths
from contracts.data_products import (
    wholesale_sap,
    wholesale_results,
    wholesale_settlement_reports,
)
from contracts.wholesale_internal import (
    succeeded_external_calculations_v1,
)
from package.databases.wholesale_results_internal.schemas import (
    energy_schema,
    energy_per_brp_schema,
    energy_per_es_schema,
    grid_loss_metering_point_time_series_schema,
    exchange_per_neighbor_schema,
    amounts_per_charge_schema,
    monthly_amounts_schema_uc,
    total_monthly_amounts_schema_uc,
)

# TODO BJM: Remove when we only use Unity Catalog
schema_config = [
    Schema(
        name=paths.WholesaleInternalDatabase.DATABASE_NAME,
        tables=[
            Table(
                name=paths.WholesaleInternalDatabase.CALCULATIONS_TABLE_NAME,
                schema=internal_schemas.calculations_schema,
            ),
            Table(
                name=paths.WholesaleInternalDatabase.GRID_LOSS_METERING_POINT_IDS_TABLE_NAME,
                schema=internal_schemas.grid_loss_metering_point_ids_schema,
            ),
            Table(
                name=paths.WholesaleInternalDatabase.CALCULATION_GRID_AREAS_TABLE_NAME,
                schema=internal_schemas.calculation_grid_areas_schema,
            ),
        ],
        views=[
            View(
                name=paths.WholesaleInternalDatabase.SUCCEEDED_EXTERNAL_CALCULATIONS_V1_VIEW_NAME,
                schema=succeeded_external_calculations_v1,
            ),
        ],
    ),
    Schema(
        name=paths.WholesaleResultsInternalDatabase.DATABASE_NAME,
        tables=[
            Table(
                name=paths.WholesaleResultsInternalDatabase.ENERGY_TABLE_NAME,
                schema=energy_schema,
            ),
            Table(
                name=paths.WholesaleResultsInternalDatabase.ENERGY_PER_BRP_TABLE_NAME,
                schema=energy_per_brp_schema,
            ),
            Table(
                name=paths.WholesaleResultsInternalDatabase.ENERGY_PER_ES_TABLE_NAME,
                schema=energy_per_es_schema,
            ),
            Table(
                name=paths.WholesaleResultsInternalDatabase.EXCHANGE_PER_NEIGHBOR_TABLE_NAME,
                schema=exchange_per_neighbor_schema,
            ),
            Table(
                name=paths.WholesaleResultsInternalDatabase.GRID_LOSS_METERING_POINT_TIME_SERIES_TABLE_NAME,
                schema=grid_loss_metering_point_time_series_schema,
            ),
            Table(
                name=paths.WholesaleResultsInternalDatabase.AMOUNTS_PER_CHARGE_TABLE_NAME,
                schema=amounts_per_charge_schema,
            ),
            Table(
                name=paths.WholesaleResultsInternalDatabase.MONTHLY_AMOUNTS_PER_CHARGE_TABLE_NAME,
                schema=monthly_amounts_schema_uc,
            ),
            Table(
                name=paths.WholesaleResultsInternalDatabase.TOTAL_MONTHLY_AMOUNTS_TABLE_NAME,
                schema=total_monthly_amounts_schema_uc,
            ),
        ],
        views=[],
    ),
    Schema(
        name=paths.WholesaleBasisDataInternalDatabase.DATABASE_NAME,
        tables=[
            Table(
                name=paths.WholesaleBasisDataInternalDatabase.METERING_POINT_PERIODS_TABLE_NAME,
                schema=basis_data_schemas.metering_point_periods_schema,
            ),
            Table(
                name=paths.WholesaleBasisDataInternalDatabase.TIME_SERIES_POINTS_TABLE_NAME,
                schema=basis_data_schemas.time_series_points_schema,
            ),
            Table(
                name=paths.WholesaleBasisDataInternalDatabase.CHARGE_LINK_PERIODS_TABLE_NAME,
                schema=basis_data_schemas.charge_link_periods_schema,
            ),
            Table(
                name=paths.WholesaleBasisDataInternalDatabase.CHARGE_PRICE_INFORMATION_PERIODS_TABLE_NAME,
                schema=basis_data_schemas.charge_price_information_periods_schema,
            ),
            Table(
                name=paths.WholesaleBasisDataInternalDatabase.CHARGE_PRICE_POINTS_TABLE_NAME,
                schema=basis_data_schemas.charge_price_points_schema,
            ),
        ],
        views=[],
    ),
    Schema(
        name=paths.WholesaleResultsDatabase.DATABASE_NAME,
        tables=[],
        views=[
            View(
                name=paths.WholesaleResultsDatabase.ENERGY_V1_VIEW_NAME,
                schema=wholesale_results.energy_v1,
            ),
            View(
                name=paths.WholesaleResultsDatabase.ENERGY_PER_BRP_V1_VIEW_NAME,
                schema=wholesale_results.energy_per_brp_v1,
            ),
            View(
                name=paths.WholesaleResultsDatabase.ENERGY_PER_ES_V1_VIEW_NAME,
                schema=wholesale_results.energy_per_es_v1,
            ),
            View(
                name=paths.WholesaleResultsDatabase.EXCHANGE_PER_NEIGHBOR_V1_VIEW_NAME,
                schema=wholesale_results.exchange_per_neighbor_v1,
            ),
            View(
                name=paths.WholesaleResultsDatabase.GRID_LOSS_METERING_POINT_TIME_SERIES_VIEW_NAME,
                schema=wholesale_results.grid_loss_metering_point_time_series_v1,
            ),
            View(
                name=paths.WholesaleResultsDatabase.AMOUNTS_PER_CHARGE_V1_VIEW_NAME,
                schema=wholesale_results.amounts_per_charge_v1,
            ),
            View(
                name=paths.WholesaleResultsDatabase.MONTHLY_AMOUNTS_PER_CHARGE_V1_VIEW_NAME,
                schema=wholesale_results.monthly_amounts_per_charge_v1,
            ),
            View(
                name=paths.WholesaleResultsDatabase.TOTAL_MONTHLY_AMOUNTS_V1_VIEW_NAME,
                schema=wholesale_results.total_monthly_amounts_v1,
            ),
        ],
    ),
    Schema(
        name=paths.WholesaleSettlementReportsDatabase.DATABASE_NAME,
        tables=[],
        views=[
            View(
                name=paths.WholesaleSettlementReportsDatabase.METERING_POINT_PERIODS_VIEW_NAME_V1,
                schema=wholesale_settlement_reports.metering_point_periods_v1,
            ),
            View(
                name=paths.WholesaleSettlementReportsDatabase.METERING_POINT_TIME_SERIES_VIEW_NAME_V1,
                schema=wholesale_settlement_reports.metering_point_time_series_v1,
            ),
            View(
                name=paths.WholesaleSettlementReportsDatabase.CHARGE_PRICES_VIEW_NAME_V1,
                schema=wholesale_settlement_reports.charge_prices_v1,
            ),
            View(
                name=paths.WholesaleSettlementReportsDatabase.CHARGE_LINK_PERIODS_VIEW_NAME_V1,
                schema=wholesale_settlement_reports.charge_link_periods_v1,
            ),
            View(
                name=paths.WholesaleSettlementReportsDatabase.AMOUNTS_PER_CHARGE_V1_VIEW_NAME,
                schema=wholesale_settlement_reports.amounts_per_charge_v1,
            ),
            View(
                name=paths.WholesaleSettlementReportsDatabase.MONTHLY_AMOUNTS_PER_CHARGE_V1_VIEW_NAME,
                schema=wholesale_settlement_reports.monthly_amounts_per_charge_v1,
            ),
            View(
                name=paths.WholesaleSettlementReportsDatabase.TOTAL_MONTHLY_AMOUNTS_V1_VIEW_NAME,
                schema=wholesale_settlement_reports.total_monthly_amounts_v1,
            ),
            View(
                # ToDo JMG: Remove when settlement report subsystem uses monthly_amounts_per_charge_v1/total_monthly_amounts_v1
                name=paths.WholesaleSettlementReportsDatabase.MONTHLY_AMOUNTS_V1_VIEW_NAME,
                schema=wholesale_settlement_reports.monthly_amounts_v1,
            ),
        ],
    ),
    Schema(
        name=paths.WholesaleSapDatabase.DATABASE_NAME,
        tables=[],
        views=[
            View(
                name=paths.WholesaleSapDatabase.LATEST_CALCULATIONS_HISTORY_V1_VIEW_NAME,
                schema=wholesale_sap.latest_calculations_history_v1,
            ),
            View(
                name=paths.WholesaleSapDatabase.ENERGY_V1_VIEW_NAME,
                schema=wholesale_sap.energy_v1,
            ),
            View(
                name=paths.WholesaleSapDatabase.AMOUNTS_PER_CHARGE_V1_VIEW_NAME,
                schema=wholesale_sap.amounts_per_charge_v1,
            ),
        ],
    ),
]
