name: Include Databricks assets in release
description: Include Databricks assets in release package together with wheel distribution

inputs:
  wheel_working_directory:
    description: Path to wheel working directory
    required: true

runs:
  using: composite
  steps:
    - name: Call include assets script
      shell: pwsh
      run: |
        . ${{ github.action_path }}/Add-Assets.ps1
        # Do it for each subdirectory in the wheel working directory
        Get-ChildItem -Directory -Path ${{ inputs.wheel_working_directory }} | ForEach-Object {
          Add-Assets -WorkingDirectory $_.FullName
        }
