ALTER TABLE Batch
ALTER COLUMN PeriodStart DATETIME2 NOT NULL;
ALTER TABLE Batch
    ADD CONSTRAINT df_batch_periodstart DEFAULT '2022-05-31T22:00:00' FOR PeriodStart;
ALTER TABLE Batch
ALTER COLUMN PeriodEnd DATETIME2 NOT NULL;
ALTER TABLE Batch
    ADD CONSTRAINT df_batch_periodend DEFAULT '2022-06-01T22:00:00' FOR PeriodEnd;
GO 