module "app_health_checks_ui" {
  source = "git::https://github.com/Energinet-DataHub/geh-terraform-modules.git//azure/app-service?ref=v13"

  app_settings = {
    # Health Checks to monitor
    # Ready - prefix with 0xx
    "HealthChecksUI__HealthChecks__000__Name" = "health-checks-ui:::Health Check UI"
    "HealthChecksUI__HealthChecks__000__Uri"  = "https://app-healthchecksui-health-${lower(var.environment_short)}-we-${lower(var.environment_instance)}.azurewebsites.net/monitor/ready"
    "HealthChecksUI__HealthChecks__001__Name" = "greenforce-frontend:::Web API"
    "HealthChecksUI__HealthChecks__001__Uri"  = "https://app-bff-fe-${lower(var.environment_short)}-we-${lower(var.environment_instance)}.azurewebsites.net/monitor/ready"
    "HealthChecksUI__HealthChecks__002__Name" = "geh-market-participant:::Web API"
    "HealthChecksUI__HealthChecks__002__Uri"  = "https://app-webapi-markpart-${lower(var.environment_short)}-we-${lower(var.environment_instance)}.azurewebsites.net/monitor/ready"
    "HealthChecksUI__HealthChecks__003__Name" = "geh-market-participant:::Function"
    "HealthChecksUI__HealthChecks__003__Uri"  = "https://func-organization-markpart-${lower(var.environment_short)}-we-${lower(var.environment_instance)}.azurewebsites.net/api/monitor/ready"
    "HealthChecksUI__HealthChecks__004__Name" = "opengeh-edi:::Web API"
    "HealthChecksUI__HealthChecks__004__Uri"  = "https://func-api-edi-${lower(var.environment_short)}-we-${lower(var.environment_instance)}.azurewebsites.net/api/monitor/ready"
    "HealthChecksUI__HealthChecks__005__Name" = "opengeh-migrations:::Dropzoneunzipper Function"
    "HealthChecksUI__HealthChecks__005__Uri"  = "https://func-dropzoneunzipper-mig-${lower(var.environment_short)}-we-${lower(var.environment_instance)}.azurewebsites.net/api/monitor/ready"
    "HealthChecksUI__HealthChecks__006__Name" = "opengeh-migrations:::Timeseries Synchronization Function"
    "HealthChecksUI__HealthChecks__006__Uri"  = "https://func-timeseriessynchronization-mig-${lower(var.environment_short)}-we-${lower(var.environment_instance)}.azurewebsites.net/api/monitor/ready"
    "HealthChecksUI__HealthChecks__007__Name" = "opengeh-migrations:::Timeseries API"
    "HealthChecksUI__HealthChecks__007__Uri"  = "https://app-timeseriesapi-mig-${lower(var.environment_short)}-we-${lower(var.environment_instance)}.azurewebsites.net/monitor/ready"
    "HealthChecksUI__HealthChecks__008__Name" = "opengeh-esett-exchange:::ECP Inbox Function"
    "HealthChecksUI__HealthChecks__008__Uri"  = "https://func-ecp-inbox-esett-${lower(var.environment_short)}-we-${lower(var.environment_instance)}.azurewebsites.net/api/monitor/ready"
    "HealthChecksUI__HealthChecks__009__Name" = "opengeh-esett-exchange:::ECP Outbound Function"
    "HealthChecksUI__HealthChecks__009__Uri"  = "https://func-ecp-outbox-esett-${lower(var.environment_short)}-we-${lower(var.environment_instance)}.azurewebsites.net/api/monitor/ready"
    "HealthChecksUI__HealthChecks__010__Name" = "opengeh-esett-exchange:::Exchange Event Receiver Function"
    "HealthChecksUI__HealthChecks__010__Uri"  = "https://func-exchange-event-receiver-esett-${lower(var.environment_short)}-we-${lower(var.environment_instance)}.azurewebsites.net/api/monitor/ready"
    "HealthChecksUI__HealthChecks__011__Name" = "opengeh-esett-exchange:::Peek Function"
    "HealthChecksUI__HealthChecks__011__Uri"  = "https://func-peek-esett-${lower(var.environment_short)}-we-${lower(var.environment_instance)}.azurewebsites.net/api/monitor/ready"
    "HealthChecksUI__HealthChecks__012__Name" = "opengeh-esett-exchange:::Web API"
    "HealthChecksUI__HealthChecks__012__Uri"  = "https://app-webapi-esett-${lower(var.environment_short)}-we-${lower(var.environment_instance)}.azurewebsites.net/monitor/ready"
    "HealthChecksUI__HealthChecks__013__Name" = "opengeh-wholesale:::Web API"
    "HealthChecksUI__HealthChecks__013__Uri"  = "https://app-webapi-wholsal-${lower(var.environment_short)}-we-${lower(var.environment_instance)}.azurewebsites.net/monitor/ready"
    "HealthChecksUI__HealthChecks__014__Name" = "esett-deprecated:::Importer Web App"
    "HealthChecksUI__HealthChecks__014__Uri"  = "https://app-importer-esettdepr-${lower(var.environment_short)}-we-${lower(var.environment_instance)}.azurewebsites.net/monitor/ready"
    "HealthChecksUI__HealthChecks__015__Name" = "esett-deprecated:::BiztalkShipper Function"
    "HealthChecksUI__HealthChecks__015__Uri"  = "https://func-biztalkshipper-esettdepr-${lower(var.environment_short)}-we-${lower(var.environment_instance)}.azurewebsites.net/api/monitor/ready"
    "HealthChecksUI__HealthChecks__016__Name" = "esett-deprecated:::Receiver Function"
    "HealthChecksUI__HealthChecks__016__Uri"  = "https://func-biztalkreceiver-esettdepr-${lower(var.environment_short)}-we-${lower(var.environment_instance)}.azurewebsites.net/api/monitor/ready"
    "HealthChecksUI__HealthChecks__017__Name" = "esett-deprecated:::ChangeObserver Function"
    "HealthChecksUI__HealthChecks__017__Uri"  = "https://func-changeobserver-esettdepr-${lower(var.environment_short)}-we-${lower(var.environment_instance)}.azurewebsites.net/api/monitor/ready"
    "HealthChecksUI__HealthChecks__018__Name" = "esett-deprecated:::Converter Function"
    "HealthChecksUI__HealthChecks__018__Uri"  = "https://func-converter-esettdepr-${lower(var.environment_short)}-we-${lower(var.environment_instance)}.azurewebsites.net/api/monitor/ready"
    "HealthChecksUI__HealthChecks__018__Name" = "esett-deprecated:::EnrichmentIngestor Function"
    "HealthChecksUI__HealthChecks__018__Uri"  = "https://func-enrichmentingestor-esettdepr-${lower(var.environment_short)}-we-${lower(var.environment_instance)}.azurewebsites.net/api/monitor/ready"
    "HealthChecksUI__HealthChecks__019__Name" = "geh-market-participant:::Certificate Synchronization"
    "HealthChecksUI__HealthChecks__019__Uri"  = "https://func-certificatesynchronization-markpart-${lower(var.environment_short)}-we-${lower(var.environment_instance)}.azurewebsites.net/api/monitor/ready"
    "HealthChecksUI__HealthChecks__020__Name" = "dh2-bridge:::Send Grid loss Function"
    "HealthChecksUI__HealthChecks__020__Uri"  = "https://func-grid-loss-sender-dh2brdg-${lower(var.environment_short)}-we-${lower(var.environment_instance)}.azurewebsites.net/api/monitor/ready"
    "HealthChecksUI__HealthChecks__021__Name" = "dh2-bridge:::Peek Grid loss Function"
    "HealthChecksUI__HealthChecks__021__Uri"  = "https://func-grid-loss-peek-dh2brdg-${lower(var.environment_short)}-we-${lower(var.environment_instance)}.azurewebsites.net/api/monitor/ready"
    "HealthChecksUI__HealthChecks__022__Name" = "dh2-bridge:::Event Receiver Grid loss Function"
    "HealthChecksUI__HealthChecks__022__Uri"  = "https://func-grid-loss-event-receiver-dh2brdg-${lower(var.environment_short)}-we-${lower(var.environment_instance)}.azurewebsites.net/api/monitor/ready"
    # Live - prefix with 2xx
    "HealthChecksUI__HealthChecks__200__Name" = "health-checks-ui:::Health Check UI - live"
    "HealthChecksUI__HealthChecks__200__Uri"  = "https://app-healthchecksui-health-${lower(var.environment_short)}-we-${lower(var.environment_instance)}.azurewebsites.net/monitor/live"
    "HealthChecksUI__HealthChecks__201__Name" = "greenforce-frontend:::Web API - live"
    "HealthChecksUI__HealthChecks__201__Uri"  = "https://app-bff-fe-${lower(var.environment_short)}-we-${lower(var.environment_instance)}.azurewebsites.net/monitor/live"
    "HealthChecksUI__HealthChecks__202__Name" = "geh-market-participant:::Web API - live"
    "HealthChecksUI__HealthChecks__202__Uri"  = "https://app-webapi-markpart-${lower(var.environment_short)}-we-${lower(var.environment_instance)}.azurewebsites.net/monitor/live"
    "HealthChecksUI__HealthChecks__203__Name" = "geh-market-participant:::Function - live"
    "HealthChecksUI__HealthChecks__203__Uri"  = "https://func-organization-markpart-${lower(var.environment_short)}-we-${lower(var.environment_instance)}.azurewebsites.net/api/monitor/live"
    "HealthChecksUI__HealthChecks__204__Name" = "opengeh-edi:::Web API - live"
    "HealthChecksUI__HealthChecks__204__Uri"  = "https://func-api-edi-${lower(var.environment_short)}-we-${lower(var.environment_instance)}.azurewebsites.net/api/monitor/live"
    "HealthChecksUI__HealthChecks__205__Name" = "opengeh-migrations:::Dropzoneunzipper Function - live"
    "HealthChecksUI__HealthChecks__205__Uri"  = "https://func-dropzoneunzipper-mig-${lower(var.environment_short)}-we-${lower(var.environment_instance)}.azurewebsites.net/api/monitor/live"
    "HealthChecksUI__HealthChecks__206__Name" = "opengeh-migrations:::Timeseries Synchronization Function - live"
    "HealthChecksUI__HealthChecks__206__Uri"  = "https://func-timeseriessynchronization-mig-${lower(var.environment_short)}-we-${lower(var.environment_instance)}.azurewebsites.net/api/monitor/live"
    "HealthChecksUI__HealthChecks__207__Name" = "opengeh-migrations:::Timeseries API - live"
    "HealthChecksUI__HealthChecks__207__Uri"  = "https://app-timeseriesapi-mig-${lower(var.environment_short)}-we-${lower(var.environment_instance)}.azurewebsites.net/monitor/live"
    "HealthChecksUI__HealthChecks__208__Name" = "opengeh-esett-exchange:::ECP Inbox Function - live"
    "HealthChecksUI__HealthChecks__208__Uri"  = "https://func-ecp-inbox-esett-${lower(var.environment_short)}-we-${lower(var.environment_instance)}.azurewebsites.net/api/monitor/live"
    "HealthChecksUI__HealthChecks__209__Name" = "opengeh-esett-exchange:::ECP Outbound Function - live"
    "HealthChecksUI__HealthChecks__209__Uri"  = "https://func-ecp-outbox-esett-${lower(var.environment_short)}-we-${lower(var.environment_instance)}.azurewebsites.net/api/monitor/live"
    "HealthChecksUI__HealthChecks__210__Name" = "opengeh-esett-exchange:::Exchange Event Receiver Function - live"
    "HealthChecksUI__HealthChecks__210__Uri"  = "https://func-exchange-event-receiver-esett-${lower(var.environment_short)}-we-${lower(var.environment_instance)}.azurewebsites.net/api/monitor/live"
    "HealthChecksUI__HealthChecks__211__Name" = "opengeh-esett-exchange:::Peek Function - live"
    "HealthChecksUI__HealthChecks__211__Uri"  = "https://func-peek-esett-${lower(var.environment_short)}-we-${lower(var.environment_instance)}.azurewebsites.net/api/monitor/live"
    "HealthChecksUI__HealthChecks__212__Name" = "opengeh-esett-exchange:::Web API - live"
    "HealthChecksUI__HealthChecks__212__Uri"  = "https://app-webapi-esett-${lower(var.environment_short)}-we-${lower(var.environment_instance)}.azurewebsites.net/monitor/live"
    "HealthChecksUI__HealthChecks__213__Name" = "opengeh-wholesale:::Web API - live"
    "HealthChecksUI__HealthChecks__213__Uri"  = "https://app-webapi-wholsal-${lower(var.environment_short)}-we-${lower(var.environment_instance)}.azurewebsites.net/monitor/live"
    "HealthChecksUI__HealthChecks__214__Name" = "esett-deprecated:::Importer Web App - live"
    "HealthChecksUI__HealthChecks__214__Uri"  = "https://app-importer-esettdepr-${lower(var.environment_short)}-we-${lower(var.environment_instance)}.azurewebsites.net/monitor/live"
    "HealthChecksUI__HealthChecks__215__Name" = "esett-deprecated:::BiztalkShipper Function - live"
    "HealthChecksUI__HealthChecks__215__Uri"  = "https://func-biztalkshipper-esettdepr-${lower(var.environment_short)}-we-${lower(var.environment_instance)}.azurewebsites.net/api/monitor/live"
    "HealthChecksUI__HealthChecks__216__Name" = "esett-deprecated:::Receiver Function - live"
    "HealthChecksUI__HealthChecks__216__Uri"  = "https://func-biztalkreceiver-esettdepr-${lower(var.environment_short)}-we-${lower(var.environment_instance)}.azurewebsites.net/api/monitor/live"
    "HealthChecksUI__HealthChecks__217__Name" = "esett-deprecated:::ChangeObserver Function - live"
    "HealthChecksUI__HealthChecks__217__Uri"  = "https://func-changeobserver-esettdepr-${lower(var.environment_short)}-we-${lower(var.environment_instance)}.azurewebsites.net/api/monitor/live"
    "HealthChecksUI__HealthChecks__218__Name" = "esett-deprecated:::Converter Function - live"
    "HealthChecksUI__HealthChecks__218__Uri"  = "https://func-converter-esettdepr-${lower(var.environment_short)}-we-${lower(var.environment_instance)}.azurewebsites.net/api/monitor/live"
    "HealthChecksUI__HealthChecks__218__Name" = "esett-deprecated:::EnrichmentIngestor Function - live"
    "HealthChecksUI__HealthChecks__218__Uri"  = "https://func-enrichmentingestor-esettdepr-${lower(var.environment_short)}-we-${lower(var.environment_instance)}.azurewebsites.net/api/monitor/live"
    "HealthChecksUI__HealthChecks__219__Name" = "geh-market-participant:::Certificate Synchronization - live"
    "HealthChecksUI__HealthChecks__219__Uri"  = "https://func-certificatesynchronization-markpart-${lower(var.environment_short)}-we-${lower(var.environment_instance)}.azurewebsites.net/api/monitor/live"
    "HealthChecksUI__HealthChecks__220__Name" = "dh2-bridge:::Send Grid loss Function - live"
    "HealthChecksUI__HealthChecks__220__Uri"  = "https://func-grid-loss-sender-dh2brdg-${lower(var.environment_short)}-we-${lower(var.environment_instance)}.azurewebsites.net/api/monitor/live"
    "HealthChecksUI__HealthChecks__221__Name" = "dh2-bridge:::Peek Grid loss Function - live"
    "HealthChecksUI__HealthChecks__221__Uri"  = "https://func-grid-loss-peek-dh2brdg-${lower(var.environment_short)}-we-${lower(var.environment_instance)}.azurewebsites.net/api/monitor/live"
    "HealthChecksUI__HealthChecks__222__Name" = "dh2-bridge:::Event Receiver Grid loss Function - live"
    "HealthChecksUI__HealthChecks__222__Uri"  = "https://func-grid-loss-event-receiver-dh2brdg-${lower(var.environment_short)}-we-${lower(var.environment_instance)}.azurewebsites.net/api/monitor/live"

    # Polling Interval
    "HealthChecksUI__EvaluationTimeinSeconds" = 60
    # Max. health status history entries returned to UI
    "HealthChecksUI__MaximumExecutionHistoriesPerEndpoint" = 30

    # Logging
    "Logging__LogLevel__Default"              = "Information"
    "Logging__LogLevel__Microsoft.AspNetCore" = "Warning"

    # Tab Title
    "TAB_TITLE" = "Health Checks UI - ${var.environment_short}-we-${var.environment_instance}"
  }
}
