module "app_health_checks_ui" {
  source = "git::https://github.com/Energinet-DataHub/geh-terraform-modules.git//azure/app-service?ref=v13"

  app_settings = {
    # Health Checks to monitor
    # Ready - prefix with 0xx
    "HealthChecksUI__HealthChecks__000__Name"  = "Health Check UI"
    "HealthChecksUI__HealthChecks__000__Uri"   = "https://app-healthchecksui-health-${lower(var.environment_short)}-we-${lower(var.environment_instance)}.azurewebsites.net/monitor/ready"
    "HealthChecksUI__HealthChecks__001__Name"  = "BFF: Web API"
    "HealthChecksUI__HealthChecks__001__Uri"   = "https://app-bff-fe-${lower(var.environment_short)}-we-${lower(var.environment_instance)}.azurewebsites.net/monitor/ready"
    "HealthChecksUI__HealthChecks__002__Name"  = "Market Participant: Web API"
    "HealthChecksUI__HealthChecks__002__Uri"   = "https://app-webapi-markpart-${lower(var.environment_short)}-we-${lower(var.environment_instance)}.azurewebsites.net/monitor/ready"
    "HealthChecksUI__HealthChecks__003__Name"  = "Market Participant: Function"
    "HealthChecksUI__HealthChecks__003__Uri"   = "https://func-organization-markpart-${lower(var.environment_short)}-we-${lower(var.environment_instance)}.azurewebsites.net/api/monitor/ready"
    "HealthChecksUI__HealthChecks__004__Name"  = "EDI: Function"
    "HealthChecksUI__HealthChecks__004__Uri"   = "https://func-api-edi-${lower(var.environment_short)}-we-${lower(var.environment_instance)}.azurewebsites.net/api/monitor/ready"
    "HealthChecksUI__HealthChecks__005__Name"  = "Migration: Dropzoneunzipper Function"
    "HealthChecksUI__HealthChecks__005__Uri"   = "https://func-dropzoneunzipper-mig-${lower(var.environment_short)}-we-${lower(var.environment_instance)}.azurewebsites.net/api/monitor/ready"
    "HealthChecksUI__HealthChecks__006__Name"  = "Migration: Timeseries Synchronization Function"
    "HealthChecksUI__HealthChecks__006__Uri"   = "https://func-timeseriessynchronization-mig-${lower(var.environment_short)}-we-${lower(var.environment_instance)}.azurewebsites.net/api/monitor/ready"
    "HealthChecksUI__HealthChecks__007__Name"  = "Migration: Timeseries API"
    "HealthChecksUI__HealthChecks__007__Uri"   = "https://app-timeseriesapi-mig-${lower(var.environment_short)}-we-${lower(var.environment_instance)}.azurewebsites.net/monitor/ready"
    "HealthChecksUI__HealthChecks__008__Name"  = "eSett: ECP Inbox Function"
    "HealthChecksUI__HealthChecks__008__Uri"   = "https://func-ecp-inbox-esett-${lower(var.environment_short)}-we-${lower(var.environment_instance)}.azurewebsites.net/api/monitor/ready"
    "HealthChecksUI__HealthChecks__009__Name"  = "eSett: ECP Outbound Function"
    "HealthChecksUI__HealthChecks__009__Uri"   = "https://func-ecp-outbox-esett-${lower(var.environment_short)}-we-${lower(var.environment_instance)}.azurewebsites.net/api/monitor/ready"
    "HealthChecksUI__HealthChecks__010__Name" = "eSett: Exchange Event Receiver Function"
    "HealthChecksUI__HealthChecks__010__Uri"  = "https://func-exchange-event-receiver-esett-${lower(var.environment_short)}-we-${lower(var.environment_instance)}.azurewebsites.net/api/monitor/ready"
    "HealthChecksUI__HealthChecks__011__Name" = "eSett: Peek Function"
    "HealthChecksUI__HealthChecks__011__Uri"  = "https://func-peek-esett-${lower(var.environment_short)}-we-${lower(var.environment_instance)}.azurewebsites.net/api/monitor/ready"
    "HealthChecksUI__HealthChecks__012__Name" = "eSett: Web API"
    "HealthChecksUI__HealthChecks__012__Uri"  = "https://app-webapi-esett-${lower(var.environment_short)}-we-${lower(var.environment_instance)}.azurewebsites.net/monitor/ready"
    "HealthChecksUI__HealthChecks__013__Name" = "Wholesale: Web API"
    "HealthChecksUI__HealthChecks__013__Uri"  = "https://app-webapi-wholsal-${lower(var.environment_short)}-we-${lower(var.environment_instance)}.azurewebsites.net/monitor/ready"
    "HealthChecksUI__HealthChecks__014__Name" = "Esett Deprecated: Importer Web App"
    "HealthChecksUI__HealthChecks__014__Uri"  = "https://app-importer-esettdepr-${lower(var.environment_short)}-we-${lower(var.environment_instance)}.azurewebsites.net/monitor/ready"
    "HealthChecksUI__HealthChecks__015__Name" = "Esett Deprecated: BiztalkShipper Web App"
    "HealthChecksUI__HealthChecks__015__Uri"  = "https://app-biztalkshipper-esettdepr-${lower(var.environment_short)}-we-${lower(var.environment_instance)}.azurewebsites.net/monitor/ready"
    "HealthChecksUI__HealthChecks__016__Name" = "Esett Deprecated: Receiver Function"
    "HealthChecksUI__HealthChecks__016__Uri"  = "https://func-biztalkreceiver-esettdepr-${lower(var.environment_short)}-we-${lower(var.environment_instance)}.azurewebsites.net/api/monitor/ready"
    "HealthChecksUI__HealthChecks__017__Name" = "Esett Deprecated: ChangeObserver Function"
    "HealthChecksUI__HealthChecks__017__Uri"  = "https://func-changeobserver-esettdepr-${lower(var.environment_short)}-we-${lower(var.environment_instance)}.azurewebsites.net/api/monitor/ready"
    "HealthChecksUI__HealthChecks__018__Name" = "Esett Deprecated: Converter Function"
    "HealthChecksUI__HealthChecks__018__Uri"  = "https://func-converter-esettdepr-${lower(var.environment_short)}-we-${lower(var.environment_instance)}.azurewebsites.net/api/monitor/ready"
    "HealthChecksUI__HealthChecks__018__Name" = "Esett Deprecated: EnrichmentIngestor Function"
    "HealthChecksUI__HealthChecks__018__Uri"  = "https://func-enrichmentingestor-esettdepr-${lower(var.environment_short)}-we-${lower(var.environment_instance)}.azurewebsites.net/api/monitor/ready"
    "HealthChecksUI__HealthChecks__019__Name" = "Market Participant: Certificate Synchronization"
    "HealthChecksUI__HealthChecks__019__Uri"  = "https://func-certificatesynchronization-markpart-${lower(var.environment_short)}-we-${lower(var.environment_instance)}.azurewebsites.net/api/monitor/ready"
    # Live - prefix with 2xx
    "HealthChecksUI__HealthChecks__200__Name" = "Health Check UI - live"
    "HealthChecksUI__HealthChecks__200__Uri"  = "https://app-healthchecksui-health-${lower(var.environment_short)}-we-${lower(var.environment_instance)}.azurewebsites.net/monitor/live"
    "HealthChecksUI__HealthChecks__201__Name" = "BFF: Web API - live"
    "HealthChecksUI__HealthChecks__201__Uri"  = "https://app-bff-fe-${lower(var.environment_short)}-we-${lower(var.environment_instance)}.azurewebsites.net/monitor/live"
    "HealthChecksUI__HealthChecks__202__Name" = "Market Participant: Web API - live"
    "HealthChecksUI__HealthChecks__202__Uri"  = "https://app-webapi-markpart-${lower(var.environment_short)}-we-${lower(var.environment_instance)}.azurewebsites.net/monitor/live"
    "HealthChecksUI__HealthChecks__203__Name" = "Market Participant: Function - live"
    "HealthChecksUI__HealthChecks__203__Uri"  = "https://func-organization-markpart-${lower(var.environment_short)}-we-${lower(var.environment_instance)}.azurewebsites.net/api/monitor/live"
    "HealthChecksUI__HealthChecks__204__Name" = "EDI: Function - live"
    "HealthChecksUI__HealthChecks__204__Uri"  = "https://func-api-edi-${lower(var.environment_short)}-we-${lower(var.environment_instance)}.azurewebsites.net/api/monitor/live"
    "HealthChecksUI__HealthChecks__205__Name" = "Migration: Dropzoneunzipper Function - live"
    "HealthChecksUI__HealthChecks__205__Uri"  = "https://func-dropzoneunzipper-mig-${lower(var.environment_short)}-we-${lower(var.environment_instance)}.azurewebsites.net/api/monitor/live"
    "HealthChecksUI__HealthChecks__206__Name" = "Migration: Timeseries Synchronization Function - live"
    "HealthChecksUI__HealthChecks__206__Uri"  = "https://func-timeseriessynchronization-mig-${lower(var.environment_short)}-we-${lower(var.environment_instance)}.azurewebsites.net/api/monitor/live"
    "HealthChecksUI__HealthChecks__207__Name" = "Migration: Timeseries API - live"
    "HealthChecksUI__HealthChecks__207__Uri"  = "https://app-timeseriesapi-mig-${lower(var.environment_short)}-we-${lower(var.environment_instance)}.azurewebsites.net/monitor/live"
    "HealthChecksUI__HealthChecks__208__Name" = "eSett: ECP Inbox Function - live"
    "HealthChecksUI__HealthChecks__208__Uri"  = "https://func-ecp-inbox-esett-${lower(var.environment_short)}-we-${lower(var.environment_instance)}.azurewebsites.net/api/monitor/live"
    "HealthChecksUI__HealthChecks__209__Name" = "eSett: ECP Outbound Function - live"
    "HealthChecksUI__HealthChecks__209__Uri"  = "https://func-ecp-outbox-esett-${lower(var.environment_short)}-we-${lower(var.environment_instance)}.azurewebsites.net/api/monitor/live"
    "HealthChecksUI__HealthChecks__210__Name" = "eSett: Exchange Event Receiver Function - live"
    "HealthChecksUI__HealthChecks__210__Uri"  = "https://func-exchange-event-receiver-esett-${lower(var.environment_short)}-we-${lower(var.environment_instance)}.azurewebsites.net/api/monitor/live"
    "HealthChecksUI__HealthChecks__211__Name" = "eSett: Peek Function - live"
    "HealthChecksUI__HealthChecks__211__Uri"  = "https://func-peek-esett-${lower(var.environment_short)}-we-${lower(var.environment_instance)}.azurewebsites.net/api/monitor/live"
    "HealthChecksUI__HealthChecks__212__Name" = "eSett: Web API - live"
    "HealthChecksUI__HealthChecks__212__Uri"  = "https://app-webapi-esett-${lower(var.environment_short)}-we-${lower(var.environment_instance)}.azurewebsites.net/monitor/live"
    "HealthChecksUI__HealthChecks__213__Name" = "Wholesale: Web API - live"
    "HealthChecksUI__HealthChecks__213__Uri"  = "https://app-webapi-wholsal-${lower(var.environment_short)}-we-${lower(var.environment_instance)}.azurewebsites.net/monitor/live"
    "HealthChecksUI__HealthChecks__214__Name" = "Esett Deprecated: Importer Web App - live"
    "HealthChecksUI__HealthChecks__214__Uri"  = "https://app-importer-esettdepr-${lower(var.environment_short)}-we-${lower(var.environment_instance)}.azurewebsites.net/monitor/live"
    "HealthChecksUI__HealthChecks__215__Name" = "Esett Deprecated: BiztalkShipper Web App - live"
    "HealthChecksUI__HealthChecks__215__Uri"  = "https://app-biztalkshipper-esettdepr-${lower(var.environment_short)}-we-${lower(var.environment_instance)}.azurewebsites.net/monitor/live"
    "HealthChecksUI__HealthChecks__216__Name" = "Esett Deprecated: Receiver Function - live"
    "HealthChecksUI__HealthChecks__216__Uri"  = "https://func-biztalkreceiver-esettdepr-${lower(var.environment_short)}-we-${lower(var.environment_instance)}.azurewebsites.net/api/monitor/live"
    "HealthChecksUI__HealthChecks__217__Name" = "Esett Deprecated: ChangeObserver Function - live"
    "HealthChecksUI__HealthChecks__217__Uri"  = "https://func-changeobserver-esettdepr-${lower(var.environment_short)}-we-${lower(var.environment_instance)}.azurewebsites.net/api/monitor/live"
    "HealthChecksUI__HealthChecks__218__Name" = "Esett Deprecated: Converter Function - live"
    "HealthChecksUI__HealthChecks__218__Uri"  = "https://func-converter-esettdepr-${lower(var.environment_short)}-we-${lower(var.environment_instance)}.azurewebsites.net/api/monitor/live"
    "HealthChecksUI__HealthChecks__218__Name" = "Esett Deprecated: EnrichmentIngestor Function - live"
    "HealthChecksUI__HealthChecks__218__Uri"  = "https://func-enrichmentingestor-esettdepr-${lower(var.environment_short)}-we-${lower(var.environment_instance)}.azurewebsites.net/api/monitor/live"
    "HealthChecksUI__HealthChecks__219__Name" = "Market Participant: Certificate Synchronization - live"
    "HealthChecksUI__HealthChecks__219__Uri"  = "https://func-certificatesynchronization-markpart-${lower(var.environment_short)}-we-${lower(var.environment_instance)}.azurewebsites.net/api/monitor/live"

    # Polling Interval
    "HealthChecksUI__EvaluationTimeinSeconds" = 60
    # Max. health status history entries returned to UI
    "HealthChecksUI__MaximumExecutionHistoriesPerEndpoint" = 30

    # Logging
    "Logging__LogLevel__Default"              = "Information"
    "Logging__LogLevel__Microsoft.AspNetCore" = "Warning"

    # Tab Title
    "TAB_TITLE" = "Health Checks UI - ${var.environment_short}-we-${var.environment_instance}"
  }
}
