from Coverage.all_test_cases import Tests

# noinspection PyStatementEffect
Tests.CalculationTests.MeteringPointMasterDataUpdates.Energy_Supplier_change_on_Grid_Loss_MP
Tests.CalculationTests.MeteringPointMasterDataUpdates.Energy_Supplier_change_on_System_Correction_MP
Tests.CalculationTests.MeteringPointMasterDataUpdates.Balance_Responsible_change_on_Grid_Loss_MP
Tests.CalculationTests.MeteringPointMasterDataUpdates.Balance_Responsible_change_on_System_Correction_MP
