ALTER VIEW {SETTLEMENT_REPORT_DATABASE_NAME}.metering_point_periods RENAME TO metering_point_periods_v1
GO

ALTER VIEW {SETTLEMENT_REPORT_DATABASE_NAME}.metering_point_time_series RENAME TO metering_point_time_series_v1
GO
