from pyspark.sql.types import (
    StringType,
    StructField,
    StructType,
    TimestampType,
)

from geh_wholesale.databases.table_column_names import TableColumnNames

# This is the expected schema for the metering point periods dataframe in basis data output.
metering_point_periods_schema = StructType(
    [
        StructField(TableColumnNames.calculation_id, StringType(), False),
        StructField(TableColumnNames.metering_point_id, StringType(), False),
        StructField(TableColumnNames.metering_point_type, StringType(), False),
        StructField(TableColumnNames.settlement_method, StringType(), True),
        StructField(TableColumnNames.grid_area_code, StringType(), False),
        StructField(TableColumnNames.resolution, StringType(), False),
        StructField(TableColumnNames.from_grid_area_code, StringType(), True),
        StructField(TableColumnNames.to_grid_area_code, StringType(), True),
        StructField(TableColumnNames.parent_metering_point_id, StringType(), True),
        StructField(TableColumnNames.energy_supplier_id, StringType(), True),
        StructField(TableColumnNames.balance_responsible_party_id, StringType(), True),
        StructField(TableColumnNames.from_date, TimestampType(), False),
        StructField(TableColumnNames.to_date, TimestampType(), False),
    ]
)

# This is the expected schema for the metering point periods dataframe generated by the method get_metering_point_periods_basis_data(...).
metering_point_periods_schema_basis_data = StructType(
    [
        StructField(TableColumnNames.calculation_id, StringType(), False),
        StructField(TableColumnNames.metering_point_id, StringType(), False),
        StructField(TableColumnNames.metering_point_type, StringType(), False),
        StructField(TableColumnNames.settlement_method, StringType(), True),
        StructField(TableColumnNames.grid_area_code, StringType(), False),
        StructField(TableColumnNames.resolution, StringType(), False),
        StructField(TableColumnNames.from_grid_area_code, StringType(), True),
        StructField(TableColumnNames.to_grid_area_code, StringType(), True),
        StructField(TableColumnNames.parent_metering_point_id, StringType(), True),
        StructField(TableColumnNames.energy_supplier_id, StringType(), True),
        StructField(TableColumnNames.balance_responsible_party_id, StringType(), True),
        StructField(TableColumnNames.from_date, TimestampType(), False),
        StructField(TableColumnNames.to_date, TimestampType(), True),
    ]
)
