
class TableColumnNames:
    """This class contains all the names of the columns in the Delta tables owned my the Wholesale subsystem.

    Different tables should use the same names to ensure consistency across the subsystem.
    """

    amount = "amount"
    balance_responsible_party_id = "balance_responsible_party_id"
    charge_code = "charge_code"
    charge_key = "charge_key"
    charge_owner_id = "charge_owner_id"
    charge_price = "charge_price"
    charge_time = "charge_time"
    charge_type = "charge_type"
    calculation_execution_time_start = "calculation_execution_time_start"
    calculation_succeeded_time = "calculation_succeeded_time"
    calculation_id = "calculation_id"
    calculation_period_start = "calculation_period_start"
    calculation_period_end = "calculation_period_end"
    calculation_type = "calculation_type"
    calculation_version = "calculation_version"
    calculation_version_dh2 = "calculation_version_dh2"
    calculation_version_dh3 = "calculation_version_dh3"
    is_internal_calculation = "is_internal_calculation"
    """True if the calculation is an internal calculation, False otherwise."""
    created_by_user_id = "created_by_user_id"
    energy_supplier_id = "energy_supplier_id"
    from_date = "from_date"
    from_grid_area_code = "from_grid_area_code"
    grid_area_code = "grid_area_code"
    is_tax = "is_tax"
    metering_point_id = "metering_point_id"
    metering_point_type = "metering_point_type"
    neighbor_grid_area_code = "neighbor_grid_area_code"
    observation_time = "observation_time"
    price = "price"
    parent_metering_point_id = "parent_metering_point_id"
    quantity = "quantity"
    quantity_unit = "quantity_unit"
    quality = "quality"
    quantity_qualities = "quantity_qualities"
    resolution = "resolution"
    result_id = "result_id"
    settlement_method = "settlement_method"
    time = "time"
    time_series_type = "time_series_type"
    to_date = "to_date"
    to_grid_area_code = "to_grid_area_code"
