ALTER TABLE {BASIS_DATA_DATABASE_NAME}.calculations
ADD COLUMN created_by_user_id STRING NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000'
GO

ALTER TABLE {BASIS_DATA_DATABASE_NAME}.calculations
ADD CONSTRAINT created_by_user_id_chk CHECK (LENGTH(created_by_user_id_chk) = 36)
GO

ALTER TABLE {BASIS_DATA_DATABASE_NAME}.calculations
DROP COLUMN version
GO

ALTER TABLE {BASIS_DATA_DATABASE_NAME}.calculations
ADD COLUMN version LONG GENERATED ALWAYS AS IDENTITY START WITH 1 INCREMENT BY 1
GO
