{DATABRICKS-ONLY}DELETE FROM {CATALOG_NAME}.{WHOLESALE_BASIS_DATA_INTERNAL_DATABASE_NAME}.time_series_points
{DATABRICKS-ONLY}WHERE calculation_id IN (
{DATABRICKS-ONLY}    SELECT calculation_id
{DATABRICKS-ONLY}    FROM {CATALOG_NAME}.{WHOLESALE_INTERNAL_DATABASE_NAME}.calculations
{DATABRICKS-ONLY}    WHERE calculation_type IN ('balance_fixing', 'aggregation')
{DATABRICKS-ONLY})
{DATABRICKS-ONLY}AND metering_point_id IN (
{DATABRICKS-ONLY}    SELECT metering_point_id
{DATABRICKS-ONLY}    FROM {CATALOG_NAME}.{SHARED_WHOLESALE_INPUT_DATABASE_NAME}.metering_point_periods_view_v1
{DATABRICKS-ONLY}    WHERE type NOT IN ('E18', 'E17', 'E20')
{DATABRICKS-ONLY})

{TEST-ONLY}SELECT 1;
