{DATABRICKS-ONLY}DELETE FROM {CATALOG_NAME}.{WHOLESALE_BASIS_DATA_INTERNAL_DATABASE_NAME}.time_series_points
{DATABRICKS-ONLY}WHERE calculation_id IN (
{DATABRICKS-ONLY}    SELECT calculation_id
{DATABRICKS-ONLY}    FROM {CATALOG_NAME}.{WHOLESALE_INTERNAL_DATABASE_NAME}.calculations
{DATABRICKS-ONLY}    WHERE calculation_type IN ('balance_fixing', 'aggregation')
{DATABRICKS-ONLY})
{DATABRICKS-ONLY}AND metering_point_id IN (
{DATABRICKS-ONLY}    SELECT metering_point_id
{DATABRICKS-ONLY}    FROM {CATALOG_NAME}.{SHARED_WHOLESALE_INPUT_DATABASE_NAME}.metering_point_periods_view_v1
{DATABRICKS-ONLY}    WHERE type IN ('D01', 'D05', 'D06', 'D07', 'D08', 'D09', 'D10', 'D11', 'D12', 'D14', 'D15', 'D19')
{DATABRICKS-ONLY})

{TEST-ONLY}SELECT 1;
