# Copyright 2020 Energinet DataHub A/S
#
# Licensed under the Apache License, Version 2.0 (the "License2");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Prepare dotnet tests outputs

#
# This action is called from the 'dotnet-build-prerelease.yml' file.
#
# Prepared outputs will be zipped and uploaded as the 'dotnet-tests' artifact.
#

inputs:
  OUTPUT_PATH:
    required: true

runs:
  using: composite
  steps:
    # To ensure code coverage tooling is available in bin folder, we use publish on test assemblies
    # See https://github.com/coverlet-coverage/coverlet/issues/521#issuecomment-522429394
    - name: Publish WebApi IntegrationTests
      shell: bash
      run: |
        dotnet publish \
          '.\source\dotnet\wholesale-api\WebApi.IntegrationTests\WebApi.IntegrationTests.csproj' \
          --no-build \
          --no-restore \
          --configuration Release \
          --output '.\source\dotnet\wholesale-api\WebApi.IntegrationTests\bin\Release\net7.0'

    - name: Publish ProcessManager IntegrationTests
      shell: bash
      run: |
        dotnet publish \
          '.\source\dotnet\process-manager\ProcessManager.IntegrationTests\ProcessManager.IntegrationTests.csproj' \
          --no-build \
          --no-restore \
          --configuration Release \
          --output '.\source\dotnet\process-manager\ProcessManager.IntegrationTests\bin\Release\net7.0'

    # To ensure code coverage tooling is available in bin folder, we use publish on test assemblies
    # See https://github.com/coverlet-coverage/coverlet/issues/521#issuecomment-522429394
    - name: Publish UnitTests
      shell: bash
      run: |
        dotnet publish \
          '.\source\dotnet\wholesale-api\WebApi.UnitTests\WebApi.UnitTests.csproj' \
          --no-build \
          --no-restore \
          --configuration Release \
          --output '.\source\dotnet\wholesale-api\WebApi.UnitTests\bin\Release\net7.0'

    - name: Copy all directories and files in source/dotnet except the obj-directories
      shell: bash
      run: |
        # Create base directory
        mkdir -p '${{ inputs.OUTPUT_PATH }}/source/dotnet' ';'
        # Copy everything from source/dotnet to the new directory
        cp -a source/dotnet/. '${{ inputs.OUTPUT_PATH }}/source/dotnet'
        # Remove obj-directories from artifact
        find ${{ inputs.OUTPUT_PATH }}/ -type d -name 'obj' -exec rm -rf {} +
