name: Prepare dotnet tests outputs

#
# This action is called from the 'dotnet-build-prerelease.yml' file.
#
# Prepared outputs will be zipped and uploaded as the 'dotnet-tests' artifact.
#

inputs:
  output_path:
    required: true

runs:
  using: composite
  steps:
    - name: Copy all directories and files in source/dotnet except the obj-directories
      shell: bash
      run: |
        # Create base directory
        mkdir -p '${{ inputs.output_path }}/source/dotnet' ';'
        # Copy everything from source/dotnet to the new directory
        cp -a source/dotnet/. '${{ inputs.output_path }}/source/dotnet'
        # Remove obj-directories from artifact
        find ${{ inputs.output_path }}/ -type d -name 'obj' -exec rm -rf {} +
