name: Archive CD

on:
  push:
    branches:
      - main
    paths:
      - archive/**
      - .github/workflows/archive-cd.yml
      - .github/workflows/infrastructure-build-prerelease.yml
      - .github/workflows/infrastructure-validate.yml

jobs:
  reusable_cd:
    uses: ./.github/workflows/reusable-cd.yml
    with:
      release_name_prefix: archive_infrastructure
      event_type: archive-deployment-request-infrastructure
      team_name: TheOutlaws
    secrets: inherit
