name: EDI Infrastructure CI

on:
  pull_request:
    branches:
      - main
    paths:
      - edi/**
      - .github/workflows/edi-ci.yml
      - .github/workflows/edi-cd.yml
      - .github/workflows/infrastructure-build-prerelease.yml
      - .github/workflows/infrastructure-validate.yml
      - .github/actions/terraform-validate/*

jobs:
  #
  # Verify, build and create pre-release version of infrastructure code
  # Branch policy status check
  #
  infrastructure_ci:
    uses: ./.github/workflows/infrastructure-build-prerelease.yml
    with:
      release_name_prefix: "edi_infrastructure"
      infrastructure_path: "./edi/terraform"
    secrets: inherit
