name: Grid Loss Imbalance Prices CD

on:
  push:
    branches:
      - main
    paths:
      - grid-loss-imbalance-prices/**
      - .github/workflows/grid-loss-imbalance-prices-cd.yml
      - .github/workflows/infrastructure-build-prerelease.yml
      - .github/workflows/infrastructure-validate.yml

jobs:
  #
  # CD Infrastructure
  #

  infrastructure_promote_prerelease:
    uses: Energinet-DataHub/.github/.github/workflows/promote-prerelease.yml@v13
    with:
      release_name_prefix: grid_loss_imbalance_prices_infrastructure

  #
  # Dispatch deployment request
  #

  dispatch_deployment_event:
    runs-on: ubuntu-latest
    needs: infrastructure_promote_prerelease
    steps:
      - name: Find associated pull request
        uses: Energinet-DataHub/.github/.github/actions/find-related-pr-number@v13
        id: find_pull_request

      - uses: Energinet-DataHub/.github/.github/actions/github-create-token@v13
        name: Generate Github token
        id: generate_token
        with:
          app_id: ${{ vars.dh3serviceaccount_appid }}
          private_key: ${{ secrets.dh3serviceaccount_privatekey }}

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ steps.generate_token.outputs.token }}
          repository: ${{ vars.environment_repository_path }}
          event-type: grid-loss-imbalance-prices-deployment-request-infrastructure
          # yamllint disable-line rule:quoted-strings
          client-payload: '{"infrastructure_pr": "${{ steps.find_pull_request.outputs.pull_request_number }}"}'

  #
  # Send notification to teams channel if deployment dispatch failed
  #

  dispatch_failed:
    needs: [infrastructure_promote_prerelease, dispatch_deployment_event]
    if: |
      always() &&
      contains(needs.*.result, 'failure')
    uses: Energinet-DataHub/.github/.github/workflows/notify-team.yml@v13
    with:
      team_name: Titans
      subject: "Deployment dispatch failed: Infrastructure - Grid Loss Imbalance Prices"
    secrets: inherit
