name: Market Participant Infrastructure CI

on:
  pull_request:
    branches:
      - main
    paths:
      - market-participant/**
      - .github/workflows/market-participant-ci.yml
      - .github/workflows/market-participant-cd.yml
      - .github/workflows/infrastructure-build-prerelease.yml
      - .github/workflows/infrastructure-validate.yml
      - .github/actions/terraform-validate/*

jobs:
  #
  # Verify, build and create pre-release version of infrastructure code
  # Branch policy status check
  #
  infrastructure_ci:
    uses: ./.github/workflows/infrastructure-build-prerelease.yml
    with:
      release_name_prefix: "market_participant_infrastructure"
      infrastructure_path: "./market-participant/terraform"
    secrets: inherit
