name: Migrations Infrastructure CI

on:
  pull_request:
    branches:
      - main
    paths:
      - migrations/**
      - .github/workflows/migrations-ci.yml
      - .github/workflows/migrations-cd.yml
      - .github/workflows/infrastructure-build-prerelease.yml
      - .github/workflows/infrastructure-validate.yml
      - .github/actions/terraform-validate/*

jobs:
  #
  # Verify, build and create pre-release version of infrastructure code
  # Branch policy status check
  #
  infrastructure_ci:
    uses: ./.github/workflows/infrastructure-build-prerelease.yml
    with:
      release_name_prefix: "migrations_infrastructure"
      infrastructure_path: "./migrations/terraform"
    secrets: inherit
