name: Render C4 models with Structurizr

on:
  workflow_call: {}

jobs:
  render_c4:
    uses: Energinet-DataHub/.github/.github/workflows/structurizr-render-diagrams.yml@dstenroejl/refactor-structurizr
    with:
      structurizr_workspace_filename: views # TODO: We need another parameter to be able to specify that any changes to views.dsl + model.dsl should be detected
    secrets: inherit
