name: Reusable - CD

on:
  workflow_call:
    inputs:
      release_name_prefix:
        required: true
        type: string
      event_type:
        required: true
        type: string
      team_name:
        required: true
        type: string
jobs:
  #
  # CD Infrastructure
  #
  infrastructure_promote_prerelease:
    uses: Energinet-DataHub/.github/.github/workflows/promote-prerelease.yml@v14
    with:
      release_name_prefix: ${{ inputs.release_name_prefix }}

  #
  # Dispatch deployment request
  #
  dispatch_deployment_event:
    runs-on: ubuntu-latest
    needs: infrastructure_promote_prerelease
    steps:
      - name: Find associated pull request
        uses: Energinet-DataHub/.github/.github/actions/find-related-pr-number@v14
        id: find_pull_request

      - uses: Energinet-DataHub/.github/.github/actions/github-create-token@v14
        name: Generate Github token
        id: generate_token
        with:
          app_id: ${{ vars.dh3serviceaccount_appid }}
          private_key: ${{ secrets.dh3serviceaccount_privatekey }}

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ steps.generate_token.outputs.token }}
          repository: ${{ vars.environment_repository_path }}
          event-type: ${{ inputs.event_type }}
          # yamllint disable-line rule:quoted-strings
          client-payload: '{"infrastructure_pr": "${{ steps.find_pull_request.outputs.pull_request_number }}"}'

  #
  # Send notification to teams channel if deployment dispatch failed
  #
  dispatch_failed:
    needs: [infrastructure_promote_prerelease, dispatch_deployment_event]
    if: |
      always() &&
      contains(needs.*.result, 'failure')
    uses: Energinet-DataHub/.github/.github/workflows/notify-team.yml@v14
    with:
      team_name: ${{ inputs.team_name }}
      subject: "Deployment dispatch failed: Infrastructure - ${{ inputs.team_name }}"
    secrets: inherit
