name: Sauron CD

on:
  push:
    branches:
      - main
    paths:
      - sauron/**
      - .github/workflows/sauron-cd.yml
      - .github/workflows/infrastructure-build-prerelease.yml
      - .github/workflows/infrastructure-validate.yml

jobs:
  reusable_cd:
    uses: ./.github/workflows/reusable-cd.yml
    with:
      release_name_prefix: sauron_infrastructure
      event_type: sauron-deployment-request-infrastructure
      team_name: TeamFusion
    secrets: inherit
