name: DH UI Infrastructure CD

on:
  push:
    branches:
      - main
    paths:
      - ui/**
      - .github/workflows/ui-ci.yml
      - .github/workflows/ui-cd.yml
      - .github/workflows/infrastructure-build-prerelease.yml
      - .github/workflows/infrastructure-validate.yml

jobs:
  #
  # CD Infrastructure
  #

  infrastructure_promote_prerelease:
    uses: Energinet-DataHub/.github/.github/workflows/promote-prerelease.yml@v10
    with:
      release_name_prefix: ui_infrastructure

  #
  # Dispatch deployment request
  #

  dispatch_deploment_event:
    runs-on: ubuntu-latest
    needs: infrastructure_promote_prerelease
    steps:
      - name: Find associated pull request
        uses: Energinet-DataHub/.github/.github/actions/find-related-pr-number@v10
        id: find_pull_request

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT_TOKEN }}
          repository: "${{ secrets.DEPLOYMENT_REPOSITORY_PATH }}"
          event-type: "ui-deployment-request-infrastructure"
          client-payload: '{"infrastructure_pr": "${{ steps.find_pull_request.outputs.pull_request_number }}"}'

  #
  # Send notification to teams channel if deployment dispatch failed
  #

  dispatch_failed:
    needs: [infrastructure_promote_prerelease, dispatch_deploment_event]
    if: |
      always() &&
      contains(needs.*.result, 'failure')
    uses: Energinet-DataHub/.github/.github/workflows/notify-team.yml@v10
    with:
      team_name: "TexasRangers"
      subject: "Deployment dispatch failed: Infrastructure - UI"
    secrets: inherit
