name: Wholesale Infrastructure CI

on:
  pull_request:
    branches:
      - main
    paths:
      - wholesale/**
      - .github/workflows/wholesale-ci.yml
      - .github/workflows/wholesale-cd.yml
      - .github/workflows/infrastructure-build-prerelease.yml
      - .github/actions/terraform-validate/*

jobs:
  #
  # Verify, build and create pre-release version of infrastructure code
  # Branch policy status check
  #
  infrastructure_ci:
    uses: Energinet-DataHub/dh3-infrastructure/.github/workflows/infrastructure-build-prerelease.yml@main
    with:
      RELEASE_NAME_PREFIX: 'wholesale_infrastructure'
      INFRASTRUCTURE_PATH: './wholesale/terraform'
    secrets:
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
