#
# Zero Report for Mandalorian scheduled run
#
name: Zero Report - Scheduled

on:
  workflow_dispatch: {}
  schedule:
    # Running at 01 AM every day
    # - cron: 0 1 * * *

jobs:
  run_rat:
    runs-on: ubuntu-latest
    name: Run Zero Report
    steps:
      - uses: actions/checkout@v4

      - name: Run zero reports
        env:
          WORKING_DIRECTORY: ${{ github.workspace }}
          FROM_EMAIL: ${{ vars.email_internal_sender }}
          SENDGRID_APIKEY: ${{ secrets.sendgrid_instance_system_notifications_api_key }}
          ZENHUB_APIKEY: ${{ secrets.zenhub_apikey }}
        shell: pwsh
        run: |
          .\source\zero-reports\zero-reports.ps1
