name: Terraform Validate
inputs:
  working_directory:
    description: Working directory of the Terraform configuration
    required: true
  pat_token:
    description: Access Token
    required: true

runs:
  using: composite
  steps:
    - name: Inject PAT_TOKEN into git configuration
      shell: bash
      run: ls -ahl ${{ inputs.working_directory }}

    - name: Inject PAT_TOKEN into git configuration
      shell: bash
      run: git config --global url."https://oauth2:${{ inputs.pat_token }}@github.com".insteadOf https://github.com

    - name: Get Terraform Version
      shell: bash
      id: get-terraform-version
      run: |
        if [ -f "${{ inputs.working_directory }}/.terraform-version" ]; then
          terraform_version=`cat ${{ inputs.working_directory }}/.terraform-version`
          echo "Version found $terraform_version"
          echo "TERRAFORM_VERSION=${terraform_version}" >>$GITHUB_OUTPUT
        else
          echo "Missing file .terraform-version"
          exit 1;
        fi

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_wrapper: false
        terraform_version: ${{ steps.get-terraform-version.outputs.TERRAFORM_VERSION }}

    - name: Terraform init
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: terraform init -backend=false

    - name: Terraform validate
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: terraform validate
